[package]
name = "mendel-vectorizer"
version = "0.1.0"
authors = ["Adrián Arroyo Calle <adrian.arroyocalle@gmail.com>"]

[dependencies]
image = "*"
imageproc = "*"
cairo-rs = "0.5.0"
gdk = "*"
clap = "*"
gdk-pixbuf = "*"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_10"]
