name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install GTK3 dependencies
      run: sudo apt install libgtk-3-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
